import { ItemMast } from "@/types/item/item";

export const normalizeItem = (i: any): ItemMast => ({
    itemId: i.itemId ?? undefined,

    itemName: i.itemName ?? null,
    shortName: i.shortName ?? null,
    billName: i.billName ?? null,

    active: i.active ?? "Y",
    metalId: i.metalId ?? null,
    metalName: i.metalName ?? null,
    metalRate: i.metalRate ?? null,
    pieceRate: i.pieceRate ?? null,

    catCode: i.catCode ?? null,
    stockType: i.stockType ?? null,
    calType: i.calType ?? null,

    companyId: i.companyId ?? null,
    hsn: i.hsn ?? null,
    companyName:i.COMPANYNAME ?? null,

    userId: i.userId ?? null,
    updated: i.updated ?? null,
    uptime: i.uptime ?? null,

    allowZeroPcs: i.allowZeroPcs ?? "N",
    assorted: i.assorted ?? "N",
    autoGenerator: i.autoGenerator ?? "N",
    beeds: i.beeds ?? "N",
    bookStock: i.bookStock ?? "N",
    compliments: i.compliments ?? "N",
    coverWt: i.coverWt ?? "N",
    diaStone: i.diaStone ?? "N",
    extrAWT: i.extrAWT ?? "N",
    fixedVa: i.fixedVa ?? "N",
    focusPiece: i.focusPiece ?? "N",
    grossNetWtDiff: i.grossNetWtDiff ?? "N",
    hallMark: i.hallMark ?? "N",
    isService: i.isService ?? "N",
    maintain4C: i.maintain4C ?? "N",
    mcCalc: i.mcCalc ?? "N",
    multiMetal: i.multiMetal ?? "N",
    othCharge: i.othCharge ?? "N",
    rangeStock: i.rangeStock ?? "N",
    rateGet: i.rateGet ?? "N",
    setItem: i.setItem ?? "N",
    sizeStock: i.sizeStock ?? "N",
    stockReport: i.stockReport ?? "N",
    studded: i.studded ?? "N",
    studdedStone: i.studdedStone ?? "N",
    subItem: i.subItem ?? "N",
    tagImage: i.tagImage ?? "N",
    tagLock: i.tagLock ?? "N",
    tagType: i.tagType ?? "N",
    tagValid: i.tagValid ?? "N",
    taxInclusive: i.taxInclusive ?? "N",
    touchBased: i.touchBased ?? "N",
    valueAddedType: i.valueAddedType ?? null,
    valueCalc: i.valueCalc ?? "N",
    zeroWastage: i.zeroWastage ?? "N",

    currentStyleNo: i.currentStyleNo ?? null,
    defItemTypeId: i.defItemTypeId ?? null,
    defaultCounter: i.defaultCounter ?? null,
    defaultEmpId: i.defaultEmpId ?? null,
    discFixPer: i.discFixPer ?? null,
    discPerGm: i.discPerGm ?? null,
    discVaPer: i.discVaPer ?? null,
    fromWt: i.fromWt ?? null,
    giftValue: i.giftValue ?? null,
    gpPer: i.gpPer ?? null,
    grsWt: i.grsWt ?? null,
    marginPer: i.marginPer ?? null,
    marginValue: i.marginValue ?? null,
    netWtPer: i.netWtPer ?? null,
    noOfPiece: i.noOfPiece ?? null,
    pieceRatePur: i.pieceRatePur ?? null,
    purTouch: i.purTouch ?? null,
    salTouch: i.salTouch ?? null,
    toWt: i.toWt ?? null,

    currentTagNo: i.currentTagNo ?? null,
    endTagNo: i.endTagNo ?? null,
    itemPctPath: i.itemPctPath ?? null,
    marginIds: i.marginIds ?? null,
    pctFile: i.pctFile ?? null,
    startTag: i.startTag ?? null,
    stoneUnit: i.stoneUnit ?? null,
    studDeduct: i.studDeduct ?? null,
    styleCode: i.styleCode ?? null,
    styleNo: i.styleNo ?? null,
    tableCode: i.tableCode ?? null,
    view4C: i.view4C ?? null,
});
